routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'EmployeeController@treeView');
Route::get('/tree', 'EmployeeController@rootData')->name('tree.rootData');
Route::get('/tree/child', 'EmployeeController@childData')->name('tree.childData');
Route::group(['middleware' => 'auth'], function() {
    Route::get('/employee/list', 'EmployeeController@employeeList')->name('employee.list');
    Route::get('/getBoss', 'EmployeeController@getParent')->name('employee.create.getBoss');
    Route::get('/employee/search', 'EmployeeController@search')->name('employee.search');
    Route::post('/employee/delete', 'EmployeeController@delete')->name('employee.delete');
    Route::resource('/employee', 'EmployeeController');
});

Auth::routes();

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Employee extends Model
{
    //
    protected  $fillable = ['name', 'position_id', 'parent_id', 'start_date', 'salary', 'created_by', 'modified_by'];

    public function position()
    {
        return $this->belongsTo('App\Position');
    }

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id', 'id');
    }

}

app/Position.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    //relationship
    public function employees()
    {
        return $this->hasMany('App\Employees');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Position;
use Illuminate\Http\Request;
use App\Employee;
use Illuminate\Support\Facades\DB;

class EmployeeController extends Controller
{

    public function index()
    {

        return view('employees.index');

    }

    public function employeeList()
    {
        $collection = [];
        $nodes = DB::table('positions')
            ->join('employees', 'positions.id', '=', 'employees.position_id')
            ->select('employees.name', 'employees.id', 'positions.position_name', 'employees.start_date','employees.salary')->get();
//        $collection = collect($nodes);
//        $collection->toJson();
        foreach ($nodes as $key => $node){
            $collection['data'][$key] = collect([$node->name, $node->position_name, $node->start_date, $node->salary, $node->id]);
        }
//        dd($collection);
        return $collection;
    }

    public function create()
    {
        return view('employees.create', [
            'employee' => '',
            'positions' => Position::all(),
            'employees' => Employee::where('parent_id', '0')->get(),
            'delimiter'  => ''
        ]);
    }

    public function store(Request $request)
    {
        Employee::create($request->all());
        return redirect()->route('employee.index');
    }

    public function delete(Request $request)
    {
        Employee::where('id', $request->id)->delete();
        return redirect()->route('employee.index');
    }

    public function treeView()
    {
        return view('tree');
    }

    public function rootData()
    {

        return $this->dataBuilder(0);
    }

    public function childData(Request $request)
    {
        return $this->dataBuilder($request->id);
    }

    public function chekID($id)
    {
        return Employee::where('parent_id', $id)->count() > 0 ? true : false;
    }

    public function childrenCount($id)
    {
        $count = Employee::with('children')->where('parent_id', $id)->count();
        return  $count > 0 ?  '   || Підлеглих - ' . $count : '';
    }


    public function dataBuilder($id)
    {
        $nodes = [];
        $employees = Employee::with('position')->where('parent_id', $id)->get();

        foreach ($employees as $key => $employee){
            $nodes[$key]['id'] = $employee->id;
            $nodes[$key]['parent'] = $employee->parent_id == 0 ? '#' : $employee->parent_id;
            $nodes[$key]['text'] = $employee->name . '   ||   ' . $employee->position->position_name . $this->childrenCount($employee->id);
            $nodes[$key]['icon'] = 'fa fa-male';
            $nodes[$key]['state'] = [
                'disabled' => false,
                'opened'   => false,
            ];
            $nodes[$key]['children'] = $this->chekID($employee->id);
            $nodes[$key]['li_attr'] = [];
            $nodes[$key]['a_attr'] = [];
        }

        return response()->json($nodes);
    }

    public function getParent(Request $request)
    {
        $data = Employee::select('id', 'name')
            ->where('position_id', '=', $request->id - 1)
            ->orderBy('name','asc')
            ->get();
        return response()->json($data);
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container" style="width: 30%">

        <form class="form-horizontal" action="{{route('employee.store')}}" method="post">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('employees.partials.form')

        </form>
    </div>
@endsection

@section('script')
    <script src="{{ asset('js/dropDownChange.js') }}"></script>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')

    <div>
        <a href="{{route('employee.create')}}" class="btn btn-primary pull-left"><i class="fa fa-plus-square-o"></i>Добавити робітника</a>
    </div>

    <table class="table table-striped" id="qq">
        <thead>
        <tr>
            <th>ПІБ</th>
            <th>Посада</th>
            <th>Дата прийому</th>
            <th>Зарплата</th>
            <th class="text-center">Дія</th>
        </tr>


        </thead>
    </table>
@endsection


@section('script')
    <script src="{{ asset('js/sort.js') }}"></script>
@endsection

resources/views/employees/partials/form.blade.php
<label for="">ПІБ</label>
<input type="text" class="form-control" name="name" placeholder="Прізвище ім'я"  required>

<label for="">Посада</label>
<select class="form-control position" name="position_id">
    @foreach($positions as $position)
            <option value="{{$position->id}}">{{$position->position_name}}</option>
    @endforeach
</select>

<label for="" id="load">Начальник</label>
<select class="form-control text-left parent" name="parent_id">
    <option value="" selected="true">-------- Начальник --------</option>
</select>
<label for="">Дата початку роботи</label>
<input type="date" class="form-control" name="start_date" placeholder="Дата" required>

<label for="">Зарплата</label>
<input type="text" class="form-control" name="salary" placeholder="Зарплата"  required>

<hr />

<input class="btn btn-primary" type="submit" value="Сохранить">

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ asset('css/all.css') }}" rel="stylesheet">
    <!--JsTree 3.3.1 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.1/themes/default/style.min.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp; <li><a href="/">Дерево працівників</a></li>
                          <li><a href="{{ route('employee.index') }}">Список працівників</a></li>

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- JsTree 3.3.1 -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.1/jstree.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    @yield('script')
</body>
</html>

resources/views/tree.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div id="jstree"></div>
    </div>

@endsection

@section('script')
    <script type="text/javascript">
        $('#jstree').jstree({
            'core': {
                'data': {
                    'url' : function (node) {
                        return node.id === '#' ?
                            '{!! route('tree.rootData') !!}' : '{!! route('tree.childData') !!}';
                    },
                    'data': function (node) {
                        return {'id': node.id};
                    },
                },

                'error': function (data) {
                    $('#jstree').html('<p>We had an error...</p>');
                }
            }
        });
    </script>
@endsection